highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: rmatsum836/rmatsum836.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
title: Ray
description: Ray's portfolio (WIP)
url: https://raymatsumoto.com
author: Ray Matsumoto
twitter:
  username: sb2nov
logo: images/contents/NN.png
social:
  name: Ray Matsumoto
  links:
    - https://www.linkedin.com/in/ray-matsumoto-251a8554/
    - https://github.com/rmatsum836
